<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRycXeA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRycXeA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRycXeA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRycXeA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHRycXeA\App_KernelDevDebugContainer([
    'container.build_hash' => 'HRycXeA',
    'container.build_id' => '032fb554',
    'container.build_time' => 1685544280,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRycXeA');
