<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEYECDm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEYECDm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBEYECDm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBEYECDm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBEYECDm\App_KernelDevDebugContainer([
    'container.build_hash' => 'BEYECDm',
    'container.build_id' => '802de937',
    'container.build_time' => 1685541473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEYECDm');
